version: '3'
services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: webserver
    ports:
     - "80:80"
    depends_on:
     - app
  app:
    build:
      context: ../solution2
      dockerfile: Dockerfile.app
    container_name: go_app
